version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
          - "storybook-addon-*"
          - "@chromatic-com/*"
          - "@vueless/*"
      rollup:
        patterns:
          - "rollup"
          - "@rollup/*"
          - "rollup-plugin-*"
      biome:
        patterns:
          - "@biomejs/*"
      types:
        patterns:
          - "@types/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
